//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanCalculatorDataAccess.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVAILABILITY_MONTHS
    {
        public int ID { get; set; }
        public Nullable<int> SPAN { get; set; }
        public string SPAN_DESCRIPTION { get; set; }
    }
}
