//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanCalculatorDataAccess.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUERY_LOG
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> QUERY_DATE { get; set; }
        public Nullable<int> AGE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<int> MONTHS { get; set; }
        public Nullable<decimal> MONTHLY_PAYMENT { get; set; }
        public string QUERY_IP { get; set; }
    }
}
